import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "3615 LA BAULE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-vt323 bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
