import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "3615 LA BAULE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener('unhandledrejection', function(event) {
                // Suppress errors from known browser extensions (e.g. injectIneligible.js)
                if (event.reason && (
                  event.reason.stack?.includes('injectIneligible.js') ||
                  event.reason.message?.includes('MediaDevices is not defined')
                )) {
                  event.preventDefault();
                  console.debug('Suppressed external extension error:', event.reason);
                }
              });
              window.addEventListener('error', function(event) {
                if (event.filename?.includes('injectIneligible.js') || event.message?.includes('MediaDevices is not defined')) {
                  event.preventDefault();
                  console.debug('Suppressed external extension error:', event.message);
                }
              });
            `,
          }}
        />
      </head>
      <body
        className={`antialiased font-vt323 bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
